float:
  any:
  - base_args: ['@metric', '@dimension']
    constructor: ObjectBox
    disabled: false
    docker_tag: ann-benchmarks-objectbox
    module: ann_benchmarks.algorithms.objectbox
    name: objectbox
    run_groups:
      default:
        args: [
          [8, 16, 32, 64, 96],  # M
          [16, 32, 64, 128, 256, 512]  # ef_construction
        ]
        query_args: [
          [10, 16, 32, 64, 128, 256, 512]  # ef; 10 is the lowest possible value because we search for 10 nearest neighbors
        ]

